# Generated by Django 4.2.5 on 2023-09-06 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagemodel',
            name='number',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
